# Build stage
FROM golang:alpine AS builder
WORKDIR /app

# Install git if needed for dependencies
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Build a static binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o main ./cmd/server/main.go

# Run stage
FROM alpine:latest
WORKDIR /app

# Add tzdata and ca-certificates just in case
RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]
